version: "3"

services:
  test_helloworld:
    container_name: helloworld
    build: .
    image: helloworld:latest
    ports:
      - "8080:8080"
    volumes:
      - .:/app/
      - /app/node_modules
    environment:
      - NODE_ENV=development
